# Generated by Django 4.2.6 on 2023-10-08 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('second_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('comment', models.CharField(max_length=200, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_of_letter', models.CharField(max_length=200, verbose_name='тема письма')),
                ('body_of_letter', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='SelectFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_frequency', models.CharField(max_length=50, verbose_name='переодичность')),
            ],
            options={
                'verbose_name': 'переодичность',
                'verbose_name_plural': 'переодичности',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время рассылки')),
                ('status', models.CharField(default='создана', max_length=50, verbose_name='статус рассылки')),
                ('next_send_date', models.DateTimeField(blank=True, null=True, verbose_name='дата следующей рассылки')),
                ('client', models.ManyToManyField(to='main.client', verbose_name='клиент для рассылки')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.selectfrequency', verbose_name='переодичность рассылки')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.message', verbose_name='сообщение для рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='LogsOfMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата и время логов рассылки')),
                ('status', models.BooleanField(default=False, verbose_name='статус рассылки')),
                ('answer_from_service', models.CharField(max_length=100, verbose_name='ответ от почтового сервера')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.message', verbose_name='ссылка на сообщение')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
