# Generated by Django 4.2.6 on 2023-10-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_custompermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermissions',
            options={'permissions': [('can_disable_mailing', 'Can disable mailing')]},
        ),
    ]
