# Generated by Django 4.2.6 on 2023-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_owner_mailing_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='owner',
            new_name='owner_clients',
        ),
    ]
